# Generated by Django 6.0.3 on 2026-04-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_create_document_operation_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('client', 'Client'), ('saleslead', 'Sales Lead'), ('saleshead', 'Sales Head'), ('depthead', 'Department Head'), ('md', 'MD'), ('documentcontroller', 'Document Controller'), ('operationhead', 'Operation Head')], default='user', max_length=20),
        ),
    ]
