# Generated by Django 6.0.3 on 2026-04-08 06:00

from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def create_site_role_users(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("authentication", "UserProfile")

    credentials = [
        ("siteengineer", "siteengineer@example.com", "SiteEngineer!2026", "siteengineer"),
        ("storequeue", "storequeue@example.com", "StoreQueue!2026", "storequeue"),
    ]

    for username, email, raw_password, role in credentials:
        user, created = User.objects.get_or_create(
            username=username,
            defaults={"email": email, "is_active": True, "is_staff": False, "is_superuser": False},
        )
        if user.email != email:
            user.email = email
        user.password = make_password(raw_password)
        user.save()

        profile, _ = UserProfile.objects.get_or_create(user=user)
        profile.role = role
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_userprofile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("client", "Client"),
                    ("saleslead", "Sales Lead"),
                    ("saleshead", "Sales Head"),
                    ("depthead", "Department Head"),
                    ("md", "MD"),
                    ("documentcontroller", "Document Controller"),
                    ("operationhead", "Operation Head"),
                    ("siteengineer", "Site Engineer"),
                    ("storequeue", "Store Manager"),
                ],
                default="user",
                max_length=20,
            ),
        ),
        migrations.RunPython(create_site_role_users, migrations.RunPython.noop),
    ]
