import type { Metadata } from "next";
import InventoryAlertToaster from "./components/InventoryAlertToaster";
import PushNotificationRegistrar from "./components/PushNotificationRegistrar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Majestic",
  description: "Generated by create next app",
  icons: {
    icon: "/majesticlogo.png",
    shortcut: "/majesticlogo.png",
    apple: "/majesticlogo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <InventoryAlertToaster />
        <PushNotificationRegistrar />
        {children}
      </body>
    </html>
  );
}
