import type { Metadata } from "next";
import InventoryAlertToaster from "./components/InventoryAlertToaster";
import PushNotificationRegistrar from "./components/PushNotificationRegistrar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <InventoryAlertToaster />
        <PushNotificationRegistrar />
        {children}
      </body>
    </html>
  );
}
