# Generated by Django 6.0.3 on 2026-03-24 11:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0015_item_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='The quantity of items being entered.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_date', models.DateField(help_text='The effective date for this stock entry (used for aging).')),
                ('source_type', models.CharField(choices=[('OPENING', 'Opening Stock'), ('PURCHASE', 'Purchase Invoice'), ('SALE_RETURN', 'Sales Return'), ('ADJUSTMENT', 'Manual Adjustment')], default='OPENING', max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text='Must be False by default if Admin Approval is required.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='sales.item')),
            ],
            options={
                'verbose_name': 'Stock Entry',
                'verbose_name_plural': 'Stock Entries',
                'ordering': ['-stock_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('IN', 'India'), ('UAE', 'United Arab Emirates'), ('USA', 'United States'), ('UK', 'United Kingdom'), ('GLOBAL', 'Other Regions')], default='IN', help_text='The geographical area where this tax rate applies.', max_length=10)),
                ('item_category', models.CharField(help_text='E.g., Electronics, Essentials, Services, or Luxury Goods.', max_length=100)),
                ('tax_rate', models.DecimalField(decimal_places=2, help_text='Percentage rate (e.g., 18.00 for 18%).', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Disable this instead of deleting it to keep historical records safe.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tax Rule',
                'verbose_name_plural': 'Tax Rules',
                'unique_together': {('region', 'item_category')},
            },
        ),
    ]
