# Generated by Django 6.0.3 on 2026-03-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='stock_date',
            field=models.DateField(default='2025-10-01', help_text='The effective date for this stock entry (used for aging).'),
        ),
    ]
