# Generated by Django 6.0.3 on 2026-03-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('quantity', models.FloatField()),
                ('rate', models.FloatField()),
                ('discount_percent', models.FloatField(default=0)),
                ('tax_amount', models.FloatField()),
                ('amount', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='ledger',
        ),
        migrations.DeleteModel(
            name='Ledger',
        ),
        migrations.DeleteModel(
            name='SalesInvoice',
        ),
    ]
