# Generated by Django 6.0.3 on 2026-03-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_invoiceitem_delete_item_remove_salesinvoice_ledger_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatchdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_ref', models.CharField(max_length=50)),
                ('dispatch_docno', models.FloatField()),
                ('dispatch_through', models.CharField(max_length=20)),
                ('quantity', models.FloatField()),
                ('rate', models.FloatField()),
                ('discount_percent', models.FloatField(default=0)),
                ('tax_amount', models.FloatField()),
                ('amount', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='bill_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='ledger',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
