# Generated by Django 6.0.3 on 2026-03-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_dispatchdetails_invoiceitem_bill_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchdetails',
            name='credit_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dispatchdetails',
            name='destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dispatchdetails',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispatchdetails',
            name='dispatch_docno',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dispatchdetails',
            name='dispatch_through',
            field=models.CharField(max_length=50),
        ),
    ]
