# Generated by Django 6.0.3 on 2026-03-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_dispatchdetails_credit_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchdetails',
            name='ledger',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
