# Generated by Django 6.0.3 on 2026-03-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_dispatchdetails_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchdetails',
            name='dispatch_docno',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='dispatchdetails',
            name='sup_ref',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='item_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='invoiceitem',
            unique_together={('item_code', 'ledger', 'quantity', 'rate')},
        ),
        migrations.AddConstraint(
            model_name='dispatchdetails',
            constraint=models.UniqueConstraint(fields=('dispatch_docno', 'sup_ref'), name='unique_dispatch_record'),
        ),
    ]
