# Generated by Django 6.0.3 on 2026-03-17 12:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_dispatchdetails_dispatch_docno_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispatchdetails',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='dispatchdetails',
            name='unique_dispatch_record',
        ),
        migrations.AddField(
            model_name='dispatchdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
