# Generated by Django 6.0.3 on 2026-03-19 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_dispatchdetails_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispatchdetails',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Dispatch Details'},
        ),
        migrations.AlterUniqueTogether(
            name='invoiceitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='dispatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.dispatchdetails'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='item_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='invoiceitem',
            unique_together={('dispatch', 'item_code')},
        ),
    ]
