# Generated by Django 6.0.3 on 2026-03-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_dispatchdetails_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchdetails',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
