# Generated by Django 6.0.3 on 2026-03-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_dispatchdetails_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchdetails',
            name='terms_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatchdetails',
            name='terms_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispatchdetails',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
