# Generated by Django 6.0.3 on 2026-03-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_dispatchdetails_terms_conditions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'verbose_name_plural': 'Invoice Items'},
        ),
        migrations.AlterUniqueTogether(
            name='invoiceitem',
            unique_together=set(),
        ),
    ]
