# Generated by Django 6.0.3 on 2026-03-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_invoiceitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='invoiceitem',
            unique_together={('dispatch', 'item_code')},
        ),
    ]
