# Generated by Django 6.0.3 on 2026-03-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_alter_invoiceitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50, unique=True)),
                ('item_name', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('item_type', models.CharField(blank=True, max_length=50, null=True)),
                ('item_group', models.CharField(blank=True, max_length=50, null=True)),
                ('item_category', models.CharField(blank=True, max_length=50, null=True)),
                ('hsn_sac_code', models.CharField(blank=True, max_length=20, null=True)),
                ('mrp', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('purchase_price', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('sales_price', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('tax', models.CharField(blank=True, max_length=20, null=True)),
                ('part_no', models.CharField(blank=True, max_length=20, null=True)),
                ('batch_no', models.CharField(blank=True, max_length=20, null=True)),
                ('min_order_qty', models.IntegerField(default=1)),
                ('min_stock_qty', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('is_stock', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('need_qc', models.BooleanField(default=False)),
                ('need_service', models.BooleanField(default=False)),
                ('need_warranty', models.BooleanField(default=False)),
                ('need_serial_no', models.BooleanField(default=False)),
            ],
        ),
    ]
