# Generated by Django 6.0.3 on 2026-03-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_item_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_no', models.CharField(max_length=50, unique=True)),
                ('registered_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('client_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=150)),
                ('phone_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('email_ref_no', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name', models.CharField(max_length=150)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('payment_terms', models.CharField(max_length=100)),
                ('tax_preference', models.CharField(max_length=100)),
                ('delivery_location', models.CharField(max_length=255)),
                ('delivery_mode', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Sales Service Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
