# Generated by Django 6.0.3 on 2026-03-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_salesservicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesservicerequest',
            name='email_attachment',
            field=models.FileField(blank=True, null=True, upload_to='sales_service_attachments/'),
        ),
    ]
