# Generated by Django 6.0.3 on 2026-03-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_salesservicerequest_email_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostEstimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimation_no', models.CharField(max_length=50, unique=True)),
                ('rfq_no', models.CharField(max_length=50)),
                ('registered_date', models.DateField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('client_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=150)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('delivery_location', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_preference', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('dress_name', models.CharField(blank=True, max_length=150, null=True)),
                ('dress_code', models.CharField(blank=True, max_length=50, null=True)),
                ('dress_type', models.CharField(blank=True, max_length=50, null=True)),
                ('dress_category', models.CharField(blank=True, max_length=50, null=True)),
                ('dress_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('dress_rate', models.FloatField(default=0)),
                ('quantity', models.FloatField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('sections', models.JSONField(blank=True, default=dict)),
                ('section_totals', models.JSONField(blank=True, default=dict)),
                ('grand_total', models.FloatField(default=0)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cost Estimations',
                'ordering': ['-created_at'],
            },
        ),
    ]
