# Generated by Django 6.0.3 on 2026-03-27 06:32

from django.db import migrations, models


def seed_cost_estimation_options(apps, schema_editor):
    RawMaterialOption = apps.get_model('sales', 'RawMaterialOption')
    ProductionCostOption = apps.get_model('sales', 'ProductionCostOption')
    AddonCostOption = apps.get_model('sales', 'AddonCostOption')
    SewingCostOption = apps.get_model('sales', 'SewingCostOption')
    ThreadworkFinishingOption = apps.get_model('sales', 'ThreadworkFinishingOption')
    PackagingLogisticsOption = apps.get_model('sales', 'PackagingLogisticsOption')
    MiscellaneousOption = apps.get_model('sales', 'MiscellaneousOption')

    datasets = [
        (RawMaterialOption, [
            ("Primary Fabric", "Raw Material", "Meters", 5.00),
            ("Lining Material", "Raw Material", "Meters", 2.50),
            ("Interfacing/Fusing", "Raw Material", "Meters", 1.20),
            ("Buttons", "Raw Material", "Pieces", 0.15),
            ("Zippers", "Raw Material", "Pieces", 0.80),
            ("Main Label", "Raw Material", "Pieces", 0.10),
            ("Hangtags", "Raw Material", "Pieces", 0.05),
        ]),
        (ProductionCostOption, [
            ("Pattern Making", "Production Cost", "Per Style", 60.00),
            ("Pattern Grading", "Production Cost", "Per Size", 15.00),
            ("Cutting Labor", "Production Cost", "Per Piece", 0.40),
            ("Sampling Labor", "Production Cost", "Per Piece", 25.00),
            ("Machine Maintenance", "Production Cost", "Per Hour", 2.00),
        ]),
        (AddonCostOption, [
            ("Screen Printing", "Add-on Cost", "Per Color", 1.50),
            ("Embroidery", "Add-on Cost", "1k Stitches", 0.80),
            ("Heat Transfer", "Add-on Cost", "Per Piece", 1.10),
            ("Fabric Washing", "Add-on Cost", "Per Kg", 0.60),
            ("Special Trims", "Add-on Cost", "Meters", 0.90),
        ]),
        (SewingCostOption, [
            ("Machine Operator", "Sewing Cost", "Per Minute", 0.12),
            ("Overlock Stitching", "Sewing Cost", "Per Piece", 0.35),
            ("Flatlock Stitching", "Sewing Cost", "Per Piece", 0.50),
            ("Button Holing", "Sewing Cost", "Per Piece", 0.10),
            ("Manual Hand-work", "Sewing Cost", "Per Hour", 8.00),
        ]),
        (ThreadworkFinishingOption, [
            ("Sewing Thread", "Threadwork & Finishing", "Cones", 1.50),
            ("Thread Trimming", "Threadwork & Finishing", "Per Piece", 0.20),
            ("Ironing/Steaming", "Threadwork & Finishing", "Per Piece", 0.30),
            ("Final Inspection", "Threadwork & Finishing", "Per Piece", 0.45),
            ("Spot Cleaning", "Threadwork & Finishing", "Per Piece", 0.15),
        ]),
        (PackagingLogisticsOption, [
            ("Primary Polybag", "Packaging & Logistics", "Pieces", 0.12),
            ("Master Carton", "Packaging & Logistics", "Pieces", 2.50),
            ("Barcode Stickers", "Packaging & Logistics", "Pieces", 0.02),
            ("Courier/Freight", "Packaging & Logistics", "Per Piece", 1.25),
            ("Loading/Unloading", "Packaging & Logistics", "Per Shipment", 20.00),
        ]),
        (MiscellaneousOption, [
            ("Fabric Wastage", "Miscellaneous", "Percentage", 5.00),
            ("Utility Overhead", "Miscellaneous", "Per Month", 200.00),
            ("Admin Expenses", "Miscellaneous", "Per Piece", 0.50),
            ("Factory Insurance", "Miscellaneous", "Annual", 500.00),
            ("Buffer Margin", "Miscellaneous", "Percentage", 3.00),
        ]),
    ]

    for model, rows in datasets:
        for index, (item_name, details, unit, cost) in enumerate(rows, start=1):
            model.objects.get_or_create(
                item_name=item_name,
                defaults={
                    'details': details,
                    'unit': unit,
                    'cost': cost,
                    'display_order': index,
                    'is_active': True,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_costestimation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonCostOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(max_length=50)),
                ('cost', models.FloatField(default=0)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Add-on Cost Options',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MiscellaneousOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(max_length=50)),
                ('cost', models.FloatField(default=0)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Miscellaneous Options',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackagingLogisticsOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(max_length=50)),
                ('cost', models.FloatField(default=0)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Packaging & Logistics Options',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionCostOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(max_length=50)),
                ('cost', models.FloatField(default=0)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Production Cost Options',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RawMaterialOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(max_length=50)),
                ('cost', models.FloatField(default=0)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Raw Material Options',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SewingCostOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(max_length=50)),
                ('cost', models.FloatField(default=0)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Sewing Cost Options',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThreadworkFinishingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(max_length=50)),
                ('cost', models.FloatField(default=0)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Threadwork & Finishing Options',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.RunPython(seed_cost_estimation_options, migrations.RunPython.noop),
    ]
