# Generated by Django 6.0.3 on 2026-04-07 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0029_add_rfq_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobcard_no', models.CharField(max_length=60, unique=True)),
                ('jobcard_date', models.DateField()),
                ('rfq_no', models.CharField(blank=True, max_length=50, null=True)),
                ('cost_estimation_no', models.CharField(blank=True, max_length=50, null=True)),
                ('client_name', models.CharField(blank=True, max_length=150, null=True)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('attention', models.CharField(blank=True, max_length=150, null=True)),
                ('rfq_type', models.CharField(blank=True, max_length=100, null=True)),
                ('rfq_category', models.CharField(blank=True, max_length=100, null=True)),
                ('job_type', models.CharField(blank=True, max_length=100, null=True)),
                ('scope_type', models.CharField(blank=True, max_length=150, null=True)),
                ('scope_description', models.TextField(blank=True, null=True)),
                ('scope_remarks', models.TextField(blank=True, null=True)),
                ('planning_date', models.DateField(blank=True, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobcards', to='sales.purchaseorder')),
            ],
            options={
                'verbose_name_plural': 'Job Cards',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
