# Generated by Django 6.0.3 on 2026-04-08 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0030_jobcard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_jobcards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesservicerequest',
            name='approval_status',
            field=models.CharField(choices=[('Not Required', 'Not Required'), ('Pending Head', 'Pending Head'), ('Pending MD', 'Pending MD'), ('Approved', 'Approved')], default='Not Required', max_length=20),
        ),
        migrations.AddField(
            model_name='salesservicerequest',
            name='skip_sales_flow',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salesservicerequest',
            name='rfq_category',
            field=models.CharField(blank=True, choices=[('Standard', 'Standard'), ('Quote of Assessment', 'Quote of Assessment'), ('Quote of Completion', 'Quote of Completion')], default='Standard', max_length=50),
        ),
    ]
