# Generated by Django 6.0.3 on 2026-04-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_jobcard_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='grn_no',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
