# Generated by Django 6.0.3 on 2026-04-09 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_jobcard_grn_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationHeadRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_no', models.CharField(max_length=80, unique=True)),
                ('operation_date', models.DateField()),
                ('rfq_no', models.CharField(blank=True, max_length=50, null=True)),
                ('rfq_date', models.DateField(blank=True, null=True)),
                ('rfq_category', models.CharField(blank=True, max_length=100, null=True)),
                ('rfq_type', models.CharField(blank=True, max_length=100, null=True)),
                ('cost_estimation_no', models.CharField(blank=True, max_length=50, null=True)),
                ('cost_estimation_date', models.DateField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=150, null=True)),
                ('attention_name', models.CharField(blank=True, max_length=150, null=True)),
                ('po_no', models.CharField(blank=True, max_length=50, null=True)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('jobcard_no', models.CharField(blank=True, max_length=60, null=True)),
                ('jobcard_date', models.DateField(blank=True, null=True)),
                ('plan_start_date', models.DateField(blank=True, null=True)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('po_delivery_date', models.DateField(blank=True, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('notified_supervisor', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jobcard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_registrations', to='sales.jobcard')),
                ('shopfloor_incharge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopfloor_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Operation Head Registrations',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
