# Generated by Django 6.0.3 on 2026-04-10 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0033_operationheadregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='jobcard_status',
            field=models.CharField(default='Jobcard created', max_length=60),
        ),
        migrations.CreateModel(
            name='ShopfloorExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Execution Complete')], default='draft', max_length=32)),
                ('inspection_start_date', models.DateField(blank=True, null=True)),
                ('inspection_end_date', models.DateField(blank=True, null=True)),
                ('incoming_inspection_checklist', models.TextField(blank=True, null=True)),
                ('inspection_report', models.FileField(blank=True, null=True, upload_to='shopfloor/inspection/report')),
                ('inspection_additional_file', models.FileField(blank=True, null=True, upload_to='shopfloor/inspection/attachments')),
                ('inspection_remarks', models.TextField(blank=True, null=True)),
                ('disassembly_start_date', models.DateField(blank=True, null=True)),
                ('disassembly_end_date', models.DateField(blank=True, null=True)),
                ('assessment_start_date', models.DateField(blank=True, null=True)),
                ('assessment_end_date', models.DateField(blank=True, null=True)),
                ('assessment_spare_repair_recommended', models.TextField(blank=True, null=True)),
                ('assessment_opening_report', models.FileField(blank=True, null=True, upload_to='shopfloor/assessment/opening_report')),
                ('assessment_remarks', models.TextField(blank=True, null=True)),
                ('spare_repair_start_date', models.DateField(blank=True, null=True)),
                ('spare_repair_end_date', models.DateField(blank=True, null=True)),
                ('spare_repair_remarks', models.TextField(blank=True, null=True)),
                ('assembly_start_date', models.DateField(blank=True, null=True)),
                ('assembly_end_date', models.DateField(blank=True, null=True)),
                ('assembly_testing_report', models.FileField(blank=True, null=True, upload_to='shopfloor/assembly/testing')),
                ('assembly_job_completion_report', models.FileField(blank=True, null=True, upload_to='shopfloor/assembly/job_completion')),
                ('assembly_final_report', models.FileField(blank=True, null=True, upload_to='shopfloor/assembly/final')),
                ('assembly_shipping_checklist', models.FileField(blank=True, null=True, upload_to='shopfloor/assembly/shipping')),
                ('assembly_remarks', models.TextField(blank=True, null=True)),
                ('opening_report', models.FileField(blank=True, null=True, upload_to='shopfloor/reports/opening')),
                ('testing_report', models.FileField(blank=True, null=True, upload_to='shopfloor/reports/testing')),
                ('job_completion_report', models.FileField(blank=True, null=True, upload_to='shopfloor/reports/job_completion')),
                ('notify_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assembly_approved_by_hod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembly_approved_hod_executions', to=settings.AUTH_USER_MODEL)),
                ('assembly_done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembly_done_executions', to=settings.AUTH_USER_MODEL)),
                ('assembly_validated_by_hod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembly_validated_hod_executions', to=settings.AUTH_USER_MODEL)),
                ('assembly_validated_by_qc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembly_validated_qc_executions', to=settings.AUTH_USER_MODEL)),
                ('assessment_approved_by_hod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_approved_hod_executions', to=settings.AUTH_USER_MODEL)),
                ('assessment_done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_done_executions', to=settings.AUTH_USER_MODEL)),
                ('assessment_validated_by_hod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_validated_hod_executions', to=settings.AUTH_USER_MODEL)),
                ('assessment_validated_by_qc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_validated_qc_executions', to=settings.AUTH_USER_MODEL)),
                ('disassembly_done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disassembly_done_executions', to=settings.AUTH_USER_MODEL)),
                ('disassembly_validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disassembly_validated_executions', to=settings.AUTH_USER_MODEL)),
                ('inspection_done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_done_executions', to=settings.AUTH_USER_MODEL)),
                ('inspection_validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_validated_executions', to=settings.AUTH_USER_MODEL)),
                ('jobcard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopfloor_execution', to='sales.jobcard')),
                ('spare_repair_done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_repair_done_executions', to=settings.AUTH_USER_MODEL)),
                ('spare_repair_validated_by_qc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_repair_validated_qc_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shopfloor Execution',
                'verbose_name_plural': 'Shopfloor Executions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopfloorActivityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('internal_service', 'Internal Service Request'), ('pr_request', 'PR Request'), ('material_request', 'Material Request'), ('transport_request', 'Transport Request')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopfloor_activity_requests', to=settings.AUTH_USER_MODEL)),
                ('shopfloor_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_requests', to='sales.shopfloorexecution')),
            ],
            options={
                'verbose_name': 'Shopfloor Activity Request',
                'verbose_name_plural': 'Shopfloor Activity Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
